---
- name: install epel-release(s)
  action: yum name=epel-release state=installed
  when: ansible_os_family == "RedHat"

- name: Install nginx
  yum: pkg=nginx state=installed

- include: selinux.yml
  when: ansible_os_family == "RedHat" and selinux is defined and {{selinux}}

- name: Create letsencrypt directory in /var/www/vhosts
  file: path=/var/www/vhosts/letsencrypt state=directory mode=0755 owner=root group=root

- name: Create default vhost in /var/www/vhosts/default
  file: path=/var/www/vhosts/default state=directory mode=0755 owner=root group=root

- name: Copy nginx.conf to /etc/nginx/
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root validate="/usr/sbin/nginx -t -c %s" backup=yes
  notify:
   - restart nginx

- name: Getting state of default 404 file
  stat: path={{default_documentroot}}/{{default_404_html}}
  register: page404

- name: Make sure default 404.html exists
  file: path={{default_documentroot}}/{{default_404_html}} state=touch owner="root" group="root"
  when: not page404.stat.exists
  notify:
   - reload nginx

- name: Getting state of default 50x file
  stat: path={{default_documentroot}}/{{default_50x_html}}
  register: page50x

- name: Make sure default 50x.html exists
  file: path={{default_documentroot}}/{{default_50x_html}} state=touch owner="root" group="root"
  when: not page50x.stat.exists
  notify:
   - reload nginx

- name: Enable service Nginx
  service: name=nginx enabled=yes

- name: Start service Nginx
  service: name=nginx state=started
